const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync(require('node:path').join(__dirname, '../extension/app.js'), 'utf8');
const context = vm.createContext({});
vm.runInContext(source.split('// CARD ORDER MODEL:')[1].split('\n').slice(1).join('\n').split('// END CARD ORDER MODEL')[0] + source.split('// CARD COLUMN MODEL')[1].split('// END CARD COLUMN MODEL')[0], context);
const plain = value => JSON.parse(JSON.stringify(value));
const groups = Array.from({length:9},(_,i)=>({domain:String(i),tabs:Array(9-i).fill(1)}));
assert.deepEqual(plain(context.sortDomainCards([...groups].reverse(),{})).map(g=>g.domain),groups.map(g=>g.domain));
let layout = context.buildCardColumns(groups,{},3);
assert.deepEqual(plain(layout.columns),[['0','3','6'],['1','4','7'],['2','5','8']]);
layout=context.changeCardColumns(layout,'swap','0','1');
assert.deepEqual(plain(layout.columns),[['1','3','6'],['0','4','7'],['2','5','8']]);
layout=context.changeCardColumns(layout,'bottom','0');
assert.deepEqual(plain(layout.columns),[['1','3','6'],['4','7','0'],['2','5','8']]);
layout=context.changeCardColumns(layout,'top','7');
assert.deepEqual(plain(layout.columns),[['1','3','6'],['7','4','0'],['2','5','8']]);
const state={layouts:{3:plain(layout)}};
assert.deepEqual(plain(context.buildCardColumns(groups,state,3)),plain(layout));
const expanded=context.buildCardColumns([...groups,{domain:'9',tabs:[1]},{domain:'10',tabs:[1]}],state,3);
assert.deepEqual(plain(expanded.columns[1]),['7','4','10','0']);
const missing=context.changeCardColumns(layout,'swap','missing','0');
assert.deepEqual(plain(missing),plain(layout));
assert.deepEqual(plain(context.buildCardColumns(groups,{},1).columns),[groups.map(g=>g.domain)]);
const malformed=context.buildCardColumns(groups,{layouts:{3:{columns:[['0','0',null,'stale'],false,['0','1']],bottom:'bad'}}},3);
assert.equal(new Set(plain(malformed.columns).flat()).size,9);
assert.equal(plain(malformed.columns).flat().length,9);
console.log('Card columns: count order, cross-column swaps, local top/bottom, storage, new cards, responsive layout and invalid data passed');
