const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync(require('node:path').join(__dirname, '../extension/app.js'), 'utf8');
const context = vm.createContext({});
vm.runInContext(source.split('// CARD ORDER MODEL:')[1].split('\n').slice(1).join('\n').split('// END CARD ORDER MODEL')[0] + source.split('// CARD COLUMN MODEL')[1].split('// END CARD COLUMN MODEL')[0], context);
const plain = value => JSON.parse(JSON.stringify(value));
const groups = Array.from({length:9},(_,i)=>({domain:String(i),tabs:Array(9-i).fill(1)}));
assert.deepEqual(plain(context.sortDomainCards([...groups].reverse(),{})).map(g=>g.domain),groups.map(g=>g.domain));
let layout = context.buildCardColumns(groups,{},3);
assert.deepEqual(plain(layout.columns),[['0','3','6'],['1','4','7'],['2','5','8']]);
layout=context.changeCardColumns(layout,'swap','0','1');
assert.deepEqual(plain(layout.columns),[['1','3','6'],['0','4','7'],['2','5','8']]);
layout=context.changeCardColumns(layout,'bottom','0');
assert.deepEqual(plain(layout.columns),[['1','3','6'],['4','7','0'],['2','5','8']]);
layout=context.changeCardColumns(layout,'top','7');
assert.deepEqual(plain(layout.columns),[['1','3','6'],['7','4','0'],['2','5','8']]);
const state={layouts:{3:plain(layout)}};
assert.deepEqual(plain(context.buildCardColumns(groups,state,3)),plain(layout));
const expanded=context.buildCardColumns([...groups,{domain:'9',tabs:[1]},{domain:'10',tabs:[1]}],state,3);
assert.equal(plain(expanded.columns[1])[0],'7');
assert.equal(plain(expanded.columns[1]).at(-1),'0');
assert.equal(new Set(plain(expanded.columns).flat()).size,11);
const missing=context.changeCardColumns(layout,'swap','missing','0');
assert.deepEqual(plain(missing),plain(layout));
assert.deepEqual(plain(context.buildCardColumns(groups,{},1).columns),[groups.map(g=>g.domain)]);
const malformed=context.buildCardColumns(groups,{layouts:{3:{columns:[['0','0',null,'stale'],false,['0','1']],bottom:'bad'}}},3);
assert.equal(new Set(plain(malformed.columns).flat()).size,9);
assert.equal(plain(malformed.columns).flat().length,9);
console.log('Card columns: count order, cross-column swaps, local top/bottom, storage, new cards, responsive layout and invalid data passed');
// A saved swap must not freeze unpinned cards after tab counts change.
const beforeGrowth = ['a','b','c','d','e','github.com'].map(domain=>({domain,tabs:[1]}));
const growthLayout=context.buildCardColumns(beforeGrowth,{},3);
let growthSaved={layouts:{3:plain(context.changeCardColumns(growthLayout,'swap','a','b'))}};
const afterGrowth=beforeGrowth.map(g=>({...g,tabs:Array(g.domain==='github.com'?5:1).fill(1)}));
const promoted=context.buildCardColumns(afterGrowth,growthSaved,3);
assert.equal(plain(promoted.columns)[0][0],'github.com','Count growth must promote the previously saved bottom card');
let pinnedGrowth=context.changeCardColumns(growthLayout,'top','d');
pinnedGrowth=context.changeCardColumns(pinnedGrowth,'bottom','github.com');
const growthWithPins=context.buildCardColumns(afterGrowth,{layouts:{3:plain(pinnedGrowth)}},3);
assert.equal(plain(growthWithPins.columns)[0][0],'d','Explicit top survives count changes');
assert.equal(plain(growthWithPins.columns)[2].at(-1),'github.com','Explicit bottom survives count changes');
console.log('Tab count growth: automatic priority and explicit pins passed');

const reconciled=context.reconcileCardOrder(afterGrowth,growthSaved);
const countDecreased=context.buildCardColumns(beforeGrowth,reconciled,3);
assert.equal(plain(countDecreased.columns)[0][0],'a','Returning to old counts must not resurrect an old swap');
const legacyState={layouts:{3:{columns:[['a','d'],['b','e'],['c','github.com']],bottom:[]}}};
assert.equal(plain(context.reconcileCardOrder(afterGrowth,legacyState).layouts[3].columns)[0][0],'github.com');
console.log('Count decrease and old layout migration passed');
// Reproduce the user's existing profile: multiple legacy top pins hide the busiest card.
const stackedGroups=[{domain:'falin.top',tabs:[1]},{domain:'github.com',tabs:[1,2]},{domain:'example.test',tabs:[1]}];
const stackedSaved={layouts:{3:{columns:[['example.test'],[],['falin.top','github.com']],top:['falin.top','github.com'],bottom:[],counts:[['example.test',1],['falin.top',1],['github.com',2]]}}};
const stackedReconciled=context.reconcileCardOrder(stackedGroups,stackedSaved);
assert.equal(plain(stackedReconciled.layouts[3].columns)[2][0],'github.com','The busiest of several legacy top pins must appear at the top of its column');
console.log('Multiple legacy top pins: count priority passed');
const toggled=context.changeCardColumns(stackedReconciled.layouts[3],'top','github.com');
const unpinned=context.reconcileCardOrder(stackedGroups,{layouts:{3:plain(toggled)}}).layouts[3];
assert.equal(plain(unpinned.top).includes('github.com'),false);
assert.equal(plain(unpinned.columns)[0][0],'github.com','Cancel top pin restores default count priority');
const pinnedAgain=context.changeCardColumns(unpinned,'bottom','github.com');
assert.equal(plain(pinnedAgain.bottom).includes('github.com'),true);
const unbottom=context.changeCardColumns(pinnedAgain,'bottom','github.com');
assert.equal(plain(unbottom.bottom).includes('github.com'),false);
console.log('Pin toggles: explicit cancellation restores automatic sorting');

const globalLegacy={...stackedSaved,top:['falin.top','github.com'],order:['falin.top','github.com'],bottom:[]};
const migratedLegacy=context.reconcileCardOrder(stackedGroups,globalLegacy);
assert.equal('top' in migratedLegacy,false,'Remove global legacy pins after column migration to prevent cancelled pins resurfacing');
assert.equal(plain(migratedLegacy.layouts[3].top).includes('github.com'),true,'Migration preserves the active column pin');

// A tall first card must not receive another card while shorter columns have room.
const balanceGroups=Array.from({length:18},(_,i)=>({domain:String(i),tabs:Array(i===0?8:1).fill(1)}));
const heights=Object.fromEntries(balanceGroups.map(g=>[g.domain,g.domain==='0'?500:200]));
const balanced=context.buildCardColumns(balanceGroups,{},3,heights);
const totals=plain(balanced.columns).map(column=>column.reduce((sum,key)=>sum+heights[key],0));
assert.ok(Math.max(...totals)-Math.min(...totals)<=200,'Automatic columns must fill measured height gaps');
const swappedBalance=context.changeCardColumns(balanced,'swap','0','1');
assert.deepEqual(plain(context.buildCardColumns(balanceGroups,{layouts:{3:plain(swappedBalance)}},3,heights).columns),plain(swappedBalance.columns),'Height balancing must preserve explicit swaps');
const bottomBalance=context.changeCardColumns(balanced,'bottom','0');
const bottomColumn=plain(bottomBalance.columns).findIndex(column=>column.includes('0'));
const balancedWithBottom=context.buildCardColumns(balanceGroups,{layouts:{3:plain(bottomBalance)}},3,heights);
assert.equal(plain(balancedWithBottom.columns)[bottomColumn].at(-1),'0','Measured balancing must preserve the pinned bottom card and its column');
const bottomTotals=plain(balancedWithBottom.columns).map(column=>column.reduce((sum,key)=>sum+heights[key],0));
assert.ok(Math.max(...bottomTotals)-Math.min(...bottomTotals)<=200,'Reserve the height of pinned bottom cards when filling columns');
console.log('Measured height balance, saved swaps and pinned bottom space passed');
